# Generated by Django 5.2.1 on 2025-05-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='tier',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
