# Generated by Django 5.2.1 on 2025-05-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_alter_resident_contact_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='contact_information',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='tier',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=255, null=True),
        ),
    ]
