# Generated by Django 5.2.1 on 2025-05-20 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_alter_resident_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Annulled', 'Annulled'), ('Common-law / Live-in Partner', 'Common-law / Live-in Partner')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='contact_information',
            field=models.CharField(blank=True, default='+63', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Contact information can only contain digits (0-9) and the plus sign (+).', regex='^[0-9+]*$')]),
        ),
        migrations.AlterField(
            model_name='resident',
            name='tier',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True),
        ),
    ]
