# Generated by Django 5.2.1 on 2025-05-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_alter_resident_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Annulled', 'Annulled'), ('COMMON-LAW / LIVE-IN PARTNER', 'Common-law / Live-in Partner')], max_length=50),
        ),
    ]
