# Generated by Django 5.2.1 on 2025-05-21 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0008_resident_email_address_resident_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='purok',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resident',
            name='place_of_birth',
            field=models.TextField(),
        ),
    ]
