# Generated by Django 5.2.1 on 2025-05-29 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_resident_purok_alter_resident_place_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BARANGAY_CLEARANCE', 'Barangay Clearance'), ('CERTIFICATE_OF_RESIDENCY', 'Certificate of Residency'), ('CERTIFICATE_OF_INDIGENCY', 'Certificate of Indigency'), ('BLOTTER_COMPLAINT', 'Blotter/Complaint'), ('BUSINESS_PERMIT', 'Business Permit'), ('CONSTRUCTION_PERMIT', 'Construction Permit'), ('SENIOR_CITIZEN_ID', 'Senior Citizen ID Application'), ('PWD_ID', 'PWD ID Application'), ('OTHER', 'Other')], max_length=50)),
                ('date_filed', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the transaction was filed/requested.')),
                ('purpose', models.TextField(blank=True, help_text='Purpose of the transaction (e.g., for employment, medical assistance, local travel).', null=True)),
                ('cedula_no', models.CharField(blank=True, help_text='Cedula (Community Tax Certificate) Number, if applicable.', max_length=50, null=True)),
                ('cedula_date_issued', models.DateField(blank=True, help_text='Date Cedula was issued, if applicable.', null=True)),
                ('complainant_details', models.TextField(blank=True, help_text='Details of the complainant (e.g., name, address), if applicable (e.g., for blotter).', null=True)),
                ('respondent_name', models.CharField(blank=True, help_text='Respondent name if applicable (e.g., for blotter).', max_length=255, null=True)),
                ('incident_details', models.TextField(blank=True, help_text='Narrative or details of the incident, if applicable (e.g., for blotter). This can include place, date, and time of incident.', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Specific details of the transaction not covered by other fields (e.g., business type for permit, length of residency).')),
                ('reference_number', models.CharField(blank=True, help_text='Optional unique reference number for the transaction (e.g., OR Number, Document Control Number).', max_length=100, null=True, unique=True)),
                ('resident', models.ForeignKey(blank=True, help_text='The resident involved in the transaction. Optional for some types like general blotter entries not tied to a specific known resident initially.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_filed'],
            },
        ),
    ]
