# Generated by Django 5.2.1 on 2025-05-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0010_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cedula_date_issued',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cedula_no',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cedula_details',
            field=models.TextField(blank=True, help_text='Cedula (Community Tax Certificate) Number, if applicable.', max_length=200, null=True),
        ),
    ]
