# Generated by Django 5.2.1 on 2025-06-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0011_remove_transaction_cedula_date_issued_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the official.', max_length=255)),
                ('position', models.CharField(choices=[('PUNONG_BARANGAY', 'Punong Barangay (Barangay Captain)'), ('BARANGAY_KAGAWAD', 'Barangay Kagawad (Barangay Councilor)'), ('SK_CHAIRMAN', 'SK Chairman (Sangguniang Kabataan Chairman)'), ('BARANGAY_SECRETARY', 'Barangay Secretary'), ('BARANGAY_TREASURER', 'Barangay Treasurer'), ('CHIEF_TANOD', 'Chief Tanod (Head of Barangay Peacekeeping Force)'), ('BARANGAY_TANOD', 'Barangay Tanod (Barangay Peacekeeping Officer)'), ('LUPON_MEMBER', 'Lupon Member (Member of the Lupong Tagapamayapa)'), ('BHW', 'Barangay Health Worker (BHW)'), ('DAY_CARE_WORKER', 'Day Care Worker'), ('OTHER', 'Other Official Position')], help_text='Position held by the official.', max_length=100)),
                ('term_start_date', models.DateField(blank=True, help_text="Start date of the official's term.", null=True)),
                ('term_end_date', models.DateField(blank=True, help_text="End date of the official's term (if applicable).", null=True)),
                ('contact_number', models.CharField(blank=True, help_text='Contact number of the official.', max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, help_text='Email address of the official.', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or remarks about the official.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the official currently active in their position?')),
            ],
            options={
                'verbose_name': 'Official',
                'verbose_name_plural': 'Officials',
                'ordering': ['position', 'full_name'],
            },
        ),
    ]
