# Generated by Django 5.2.1 on 2025-06-11 04:30

from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='cloud05',
            email='cloud000argando28.com',
            password='__cloud05__'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0013_initial'), # Make sure this matches your PREVIOUS migration file
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]