# Generated by Django 5.2.1 on 2025-06-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0014_alter_official_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='position',
            field=models.CharField(choices=[('PUNONG_BARANGAY', 'Punong Barangay (Barangay Captain)'), ('BARANGAY_KAGAWAD_1', 'Barangay Kagawad 1(Barangay Councilor)'), ('BARANGAY_KAGAWAD_2', 'Barangay Kagawad 2(Barangay Councilor)'), ('BARANGAY_KAGAWAD_3', 'Barangay Kagawad 3(Barangay Councilor)'), ('BARANGAY_KAGAWAD_4', 'Barangay Kagawad 4(Barangay Councilor)'), ('BARANGAY_KAGAWAD_5', 'Barangay Kagawad 5(Barangay Councilor)'), ('BARANGAY_KAGAWAD_6', 'Barangay Kagawad 6(Barangay Councilor)'), ('BARANGAY_KAGAWAD_7', 'Barangay Kagawad 7(Barangay Councilor)'), ('BARANGAY_KAGAWAD_8', 'Barangay Kagawad 8(Barangay Councilor)'), ('SK_CHAIRMAN', 'SK Chairman (Sangguniang Kabataan Chairman)'), ('BARANGAY_SECRETARY', 'Barangay Secretary'), ('BARANGAY_TREASURER', 'Barangay Treasurer'), ('CHIEF_TANOD', 'Chief Tanod (Head of Barangay Peacekeeping Force)'), ('BARANGAY_TANOD', 'Barangay Tanod (Barangay Peacekeeping Officer)'), ('LUPON_MEMBER', 'Lupon Member (Member of the Lupong Tagapamayapa)'), ('BHW', 'Barangay Health Worker (BHW)'), ('DAY_CARE_WORKER', 'Day Care Worker'), ('OTHER', 'Other Official Position')], help_text='Position held by the official.', max_length=100),
        ),
    ]
